manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 90bca783001f216508a6cc82a891029fed1e8885
      import: app/west.yml
  self:
    path: config
